project_id = "mefyrysrlmzzcsyyysqp"

[functions.chat]
verify_jwt = false

[functions.analyze-pdf]
verify_jwt = false

[functions.veille-scraper]
verify_jwt = false

[functions.answer-with-sources]
verify_jwt = false

[functions.ingest-legal-doc]
verify_jwt = false

[functions.analyze-dum]
verify_jwt = false

[functions.analyze-product-image]
verify_jwt = false
